name: 'TestProject Execute Jobs'
description: 'Execute all the TestProject jobs in a specific project and ensure all pass.'
author: 'Mahan Fathi'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  project_id:
    description: 'Project ID'
    required: true
  api_key:
    description: 'API Key'
    required: true
  check_interval:
    description: 'Interval in seconds to check the status of running tests'
    required: false
    default: '15'
  wait_for_tests:
    description: 'Should the action wait for tests to finish before continuing'
    required: false
    default: true
  app_id:
    description: 'Application ID so we can update/pass target app url'
    required: false
    default: '0'
  app_url:
    description: 'app url (target)'
    required: false
    default: ''
branding:
  icon: 'check-circle'  
  color: 'green'
