name: 'TestProject test automation'
description: 'Execute all the TestProject jobs in a specific project and ensure all pass. and manage agent with docker'
author: 'www-norma-dev'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  project_id:
    description: 'Project ID'
    required: true
  api_key:
    description: 'API Key'
    required: true
  application_url:
    description: 'url of the application where the test-project can point'
    required: true
  check_interval:
    description: 'Interval in seconds to check the status of running tests'
    required: false
    default: '15'
  wait_for_tests:
    description: 'Should the action wait for tests to finish before continuing'
    required: false
    default: true
  agent:
    description: 'Select a default agent in the active agents in test-project'
    required: false
    default: false
  waiting_execution_time:
    description: 'This parameter allows to stop the execution after a time'
    required: false
    default: '15'
  

branding:
  icon: 'check-circle'  
  color: 'green'