name: 'TestProject Execute Jobs'
description: 'Execute all the TestProject jobs in a specific project and ensure all pass.'
author: 'Mahan Fathi'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  project_id:
    description: 'Project ID'
    required: true
  api_key:
    description: 'API Key'
    required: true
  check_interval:
    description: 'Interval in seconds to check the status of running tests'
    required: false
    default: '15'

branding:
  icon: 'check-circle'  
  color: 'green'